# fly.toml app configuration file generated for ds-sentinel-3 on 2023-12-16T19:44:20+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ds-sentinel-3"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
