# fly.toml app configuration file generated for ds-sentinel-misty-grass-622 on 2023-12-14T16:22:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ds-sentinel"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
